// Common interests for smart suggestions
export const COMMON_INTERESTS = [
  // Technology
  "Programming",
  "Web Development",
  "Mobile Apps", 
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Cybersecurity",
  "Gaming",
  "Video Games",
  "Tech Gadgets",
  "Smartphones",
  "Virtual Reality",
  "Cryptocurrency",
  "Blockchain",
  "Software Engineering",
  
  // Sports & Fitness
  "Football",
  "Basketball",
  "Soccer",
  "Tennis",
  "Baseball",
  "Golf",
  "Swimming",
  "Running",
  "Yoga",
  "Fitness",
  "Weightlifting",
  "Cycling",
  "Hiking",
  "Rock Climbing",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Martial Arts",
  "Boxing",
  "CrossFit",
  
  // Arts & Creative
  "Photography",
  "Painting",
  "Drawing",
  "Graphic Design",
  "Music",
  "Guitar",
  "Piano",
  "Singing",
  "Dancing",
  "Acting",
  "Theater",
  "Film Making",
  "Video Editing",
  "Creative Writing",
  "Poetry",
  "Sculpting",
  "Pottery",
  "Crafting",
  "DIY Projects",
  "Interior Design",
  
  // Entertainment
  "Movies",
  "TV Shows",
  "Netflix",
  "Streaming",
  "Comedy",
  "Stand-up Comedy",
  "Concerts",
  "Music Festivals",
  "Board Games",
  "Card Games",
  "Puzzle Games",
  "Video Streaming",
  "Podcasts",
  "Audiobooks",
  "Animation",
  "Anime",
  "Comics",
  "Marvel",
  "DC Comics",
  
  // Lifestyle & Hobbies
  "Cooking",
  "Baking",
  "Gardening",
  "Reading",
  "Books",
  "Travel",
  "Adventure",
  "Camping",
  "Backpacking",
  "Road Trips",
  "Fashion",
  "Style",
  "Shopping",
  "Beauty",
  "Makeup",
  "Skincare",
  "Home Decor",
  "Organization",
  "Minimalism",
  "Sustainable Living",
  
  // Food & Drink
  "Wine Tasting",
  "Coffee",
  "Tea",
  "Craft Beer",
  "Mixology",
  "Food Photography",
  "Restaurant Reviews",
  "International Cuisine",
  "Vegetarian",
  "Vegan",
  "Healthy Eating",
  "Nutrition",
  "Food Blogging",
  
  // Health & Wellness
  "Meditation",
  "Mindfulness",
  "Mental Health",
  "Wellness",
  "Self-care",
  "Therapy",
  "Life Coaching",
  "Personal Development",
  "Spirituality",
  "Alternative Medicine",
  "Holistic Health",
  
  // Professional & Career
  "Entrepreneurship",
  "Business",
  "Marketing",
  "Sales",
  "Leadership",
  "Public Speaking",
  "Networking",
  "Career Development",
  "Finance",
  "Investing",
  "Real Estate",
  "Freelancing",
  "Remote Work",
  "Startups",
  
  // Learning & Education
  "Languages",
  "Online Courses",
  "History",
  "Science",
  "Philosophy",
  "Psychology",
  "Astronomy",
  "Geography",
  "Cultural Studies",
  "Research",
  "Teaching",
  "Tutoring",
  
  // Social & Community
  "Volunteering",
  "Community Service",
  "Social Justice",
  "Environmental Activism",
  "Charity Work",
  "Event Planning",
  "Networking Events",
  "Meetups",
  "Social Media",
  "Content Creation",
  "Influencer Marketing"
];

export const INTEREST_CATEGORIES = {
  "technology": [
    "Programming", "Web Development", "Mobile Apps", "Artificial Intelligence", 
    "Machine Learning", "Data Science", "Cybersecurity", "Gaming", "Video Games",
    "Tech Gadgets", "Smartphones", "Virtual Reality", "Cryptocurrency", "Blockchain"
  ],
  "sports": [
    "Football", "Basketball", "Soccer", "Tennis", "Baseball", "Golf", "Swimming",
    "Running", "Yoga", "Fitness", "Weightlifting", "Cycling", "Hiking", 
    "Rock Climbing", "Skiing", "Snowboarding", "Surfing", "Martial Arts"
  ],
  "arts": [
    "Photography", "Painting", "Drawing", "Graphic Design", "Music", "Guitar",
    "Piano", "Singing", "Dancing", "Acting", "Theater", "Film Making",
    "Video Editing", "Creative Writing", "Poetry", "Sculpting", "Pottery"
  ],
  "entertainment": [
    "Movies", "TV Shows", "Netflix", "Streaming", "Comedy", "Stand-up Comedy",
    "Concerts", "Music Festivals", "Board Games", "Card Games", "Podcasts",
    "Audiobooks", "Animation", "Anime", "Comics"
  ],
  "lifestyle": [
    "Cooking", "Baking", "Gardening", "Reading", "Books", "Travel", "Adventure",
    "Camping", "Fashion", "Style", "Shopping", "Beauty", "Makeup", "Home Decor"
  ],
  "health": [
    "Meditation", "Mindfulness", "Mental Health", "Wellness", "Self-care",
    "Nutrition", "Healthy Eating", "Alternative Medicine", "Holistic Health"
  ],
  "professional": [
    "Entrepreneurship", "Business", "Marketing", "Sales", "Leadership",
    "Public Speaking", "Finance", "Investing", "Real Estate", "Freelancing"
  ],
  "learning": [
    "Languages", "Online Courses", "History", "Science", "Philosophy",
    "Psychology", "Astronomy", "Research", "Teaching", "Cultural Studies"
  ]
};

// Common misspellings and their corrections
export const INTEREST_SPELLING_CORRECTIONS = {
  // Technology
  "programing": "Programming",
  "programmin": "Programming", 
  "progamming": "Programming",
  "artifical intelligence": "Artificial Intelligence",
  "machien learning": "Machine Learning",
  "cybersecuirty": "Cybersecurity",
  "cyber security": "Cybersecurity",
  "blockchain": "Blockchain",
  "crypto currency": "Cryptocurrency",
  "cryptocurency": "Cryptocurrency",
  "smartphone": "Smartphones",
  "smart phone": "Smartphones",
  
  // Sports & Fitness
  "fotball": "Football",
  "soccor": "Soccer",
  "basektball": "Basketball",
  "excersize": "Fitness",
  "excercise": "Fitness",
  "weightlifing": "Weightlifting",
  "weight lifting": "Weightlifting",
  "cyling": "Cycling",
  "bicycling": "Cycling",
  "hikeing": "Hiking",
  "rock climing": "Rock Climbing",
  "skieng": "Skiing",
  "snowbording": "Snowboarding",
  "martail arts": "Martial Arts",
  "crossfit": "CrossFit",
  
  // Arts & Creative
  "photograpy": "Photography",
  "photograghy": "Photography",
  "foto": "Photography",
  "drawning": "Drawing",
  "grafic design": "Graphic Design",
  "graphic designing": "Graphic Design",
  "musics": "Music",
  "guittar": "Guitar",
  "pianno": "Piano",
  "danceing": "Dancing",
  "theatr": "Theater",
  "theatre": "Theater",
  "filmaking": "Film Making",
  "film making": "Film Making",
  "video editng": "Video Editing",
  "writting": "Creative Writing",
  "creative writting": "Creative Writing",
  "poetri": "Poetry",
  "pottary": "Pottery",
  "crafing": "Crafting",
  "diy": "DIY Projects",
  
  // Entertainment
  "moveis": "Movies",
  "tv": "TV Shows",
  "televisoin": "TV Shows",
  "netfix": "Netflix",
  "comedys": "Comedy",
  "standup": "Stand-up Comedy",
  "stand up": "Stand-up Comedy",
  "concets": "Concerts",
  "music festival": "Music Festivals",
  "boardgames": "Board Games",
  "board game": "Board Games",
  "cardgames": "Card Games",
  "card game": "Card Games",
  "podcast": "Podcasts",
  "audio books": "Audiobooks",
  "audio book": "Audiobooks",
  "animaton": "Animation",
  "comix": "Comics",
  
  // Lifestyle
  "cookng": "Cooking",
  "bakeing": "Baking",
  "gardning": "Gardening",
  "readng": "Reading",
  "book": "Books",
  "travell": "Travel",
  "traveling": "Travel",
  "travelling": "Travel",
  "adventur": "Adventure",
  "campng": "Camping",
  "fashon": "Fashion",
  "shopng": "Shopping",
  "make up": "Makeup",
  "make-up": "Makeup",
  "skincar": "Skincare",
  "skin care": "Skincare",
  "homedecor": "Home Decor",
  "home decorating": "Home Decor",
  
  // Food & Drink
  "wine tastng": "Wine Tasting",
  "coffe": "Coffee",
  "craftbeer": "Craft Beer",
  "craft beer": "Craft Beer",
  "mixalogy": "Mixology",
  "food photograpy": "Food Photography",
  "restraunt": "Restaurant Reviews",
  "resturant": "Restaurant Reviews",
  "vegeterian": "Vegetarian",
  "heath eating": "Healthy Eating",
  "nutriton": "Nutrition",
  
  // Health & Wellness
  "mediation": "Meditation",
  "mindfulnes": "Mindfulness",
  "mentalhealth": "Mental Health",
  "mental heath": "Mental Health",
  "wellnes": "Wellness",
  "selfcare": "Self-care",
  "self care": "Self-care",
  "theraphy": "Therapy",
  "lifecoaching": "Life Coaching",
  "life coaching": "Life Coaching",
  "spiritualy": "Spirituality",
  "alternativ medicine": "Alternative Medicine",
  "holistic heath": "Holistic Health",
  
  // Professional
  "entreprenurship": "Entrepreneurship",
  "entreprenuership": "Entrepreneurship",
  "busines": "Business",
  "marketting": "Marketing",
  "leaderhip": "Leadership",
  "publicspeaking": "Public Speaking",
  "public speakng": "Public Speaking",
  "networkng": "Networking",
  "carrer development": "Career Development",
  "career developement": "Career Development",
  "finace": "Finance",
  "investng": "Investing",
  "realestate": "Real Estate",
  "real estate": "Real Estate",
  "freelancng": "Freelancing",
  "remotework": "Remote Work",
  "remote work": "Remote Work",
  "start up": "Startups",
  "start-up": "Startups",
  
  // Learning
  "languges": "Languages",
  "onlinecourses": "Online Courses",
  "online course": "Online Courses",
  "histroy": "History",
  "sciene": "Science",
  "philosphy": "Philosophy",
  "psycology": "Psychology",
  "astronomie": "Astronomy",
  "geograpy": "Geography",
  "cultural studie": "Cultural Studies",
  "researh": "Research",
  "teachng": "Teaching",
  "tutorng": "Tutoring",
  
  // Social & Community
  "voluntering": "Volunteering",
  "communityservice": "Community Service",
  "community servic": "Community Service",
  "socialjustice": "Social Justice",
  "social justic": "Social Justice",
  "environmentalactivism": "Environmental Activism",
  "environmental activism": "Environmental Activism",
  "charitywork": "Charity Work",
  "charity work": "Charity Work",
  "eventplanning": "Event Planning",
  "event planning": "Event Planning",
  "meetup": "Meetups",
  "socialmedia": "Social Media",
  "social media": "Social Media",
  "contentcreation": "Content Creation",
  "content creation": "Content Creation",
  "influencermarketing": "Influencer Marketing",
  "influencer marketing": "Influencer Marketing"
};